#!/usr/bin/env python3
"""Configure Unity Android build settings for CI.

This script sets environment variables that Unity will use when building Android projects.
Unity in batch mode doesn't read preference files, so we need to use environment variables instead.
"""

import argparse
import os
import sys


def configure_gradle_env(gradle_path: str, jdk_path: str, editor_version: str):
    """Configure environment variables for Gradle and Java."""
    print(f"Configuring Gradle environment for CI")
    print(f"JDK path: {jdk_path}")
    print(f"Gradle path: {gradle_path}")
    print(f"Editor version: {editor_version}")

    # Set JAVA_HOME for Unity's Gradle build
    print(f"export JAVA_HOME={jdk_path}")
    print(f"export GRADLE_USER_HOME=$HOME/.gradle")

    # Replace Unity's bundled Gradle and JDK with the installed versions
    # This is necessary because Unity in batch mode directly uses its bundled tools
    if sys.platform == "linux":
        # Replace Gradle
        unity_gradle_path = f"/opt/unity/editors/{editor_version}/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/gradle"
        if os.path.exists(unity_gradle_path):
            print(f"Backing up Unity's bundled Gradle at {unity_gradle_path}")
            backup_path = f"{unity_gradle_path}.backup"
            if not os.path.exists(backup_path):
                os.rename(unity_gradle_path, backup_path)
            print(f"Symlinking custom Gradle from {gradle_path} to {unity_gradle_path}")
            os.symlink(gradle_path, unity_gradle_path)
            print(f"Unity will now use Gradle 8.14.1")
        else:
            print(f"Warning: Unity Gradle path not found at {unity_gradle_path}")

        # Replace OpenJDK
        unity_jdk_path = f"/opt/unity/editors/{editor_version}/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK"
        if os.path.exists(unity_jdk_path):
            print(f"Backing up Unity's bundled OpenJDK at {unity_jdk_path}")
            jdk_backup_path = f"{unity_jdk_path}.backup"
            if not os.path.exists(jdk_backup_path):
                os.rename(unity_jdk_path, jdk_backup_path)
            print(f"Symlinking custom JDK from {jdk_path} to {unity_jdk_path}")
            os.symlink(jdk_path, unity_jdk_path)
            print(f"Unity will now use Java 17")
        else:
            print(f"Warning: Unity JDK path not found at {unity_jdk_path}")

    # Configure Unity preferences for Edit Mode tests
    if sys.platform == "linux":
        # Unity on Linux stores preferences in ~/.config/unity3d/prefs
        prefs_dir = os.path.expanduser("~/.config/unity3d")
        os.makedirs(prefs_dir, exist_ok=True)
        prefs_file = os.path.join(prefs_dir, "prefs")

        # Unity uses a hash-based key system. The hash is consistent across installations
        # Format: Key_hash: value
        prefs_content = f"""JdkUseEmbedded_h4019811976: 0
JdkPath_h4019811976: {jdk_path}
GradleUseEmbedded_h4019811976: 0
GradlePath_h4019811976: {gradle_path}
AndroidSdkRoot_h4019811976: /usr/local/lib/android/sdk
AndroidNdkRoot_h4019811976: /usr/local/lib/android/sdk/ndk-bundle
"""

        # Append to existing prefs or create new file
        with open(prefs_file, "a") as f:
            f.write(prefs_content)

        print(f"Configured Unity preferences at {prefs_file}")
        print(f"  JDK: {jdk_path}")
        print(f"  Gradle: {gradle_path}")

    # Create gradle.properties in GRADLE_USER_HOME to force JDK
    gradle_home = os.path.expanduser("~/.gradle")
    os.makedirs(gradle_home, exist_ok=True)

    gradle_properties_path = os.path.join(gradle_home, "gradle.properties")
    with open(gradle_properties_path, "w") as f:
        f.write(f"# Generated by configure_unity_android.py\n")
        f.write(f"org.gradle.java.home={jdk_path}\n")

    print(f"Created {gradle_properties_path} with Java configuration")

    # Create Gradle init script to force wrapper version
    init_dir = os.path.join(gradle_home, "init.d")
    os.makedirs(init_dir, exist_ok=True)

    init_script_path = os.path.join(init_dir, "force-gradle-wrapper.gradle")
    with open(init_script_path, "w") as f:
        f.write("""// Force Gradle wrapper to use version 8.14.1
allprojects {
    tasks.withType(Wrapper) {
        gradleVersion = '8.14.1'
        distributionType = Wrapper.DistributionType.ALL
    }
}

// Patch existing wrapper properties
gradle.taskGraph.whenReady {
    gradle.taskGraph.allTasks.each { task ->
        if (task.name == 'wrapper') {
            task.doLast {
                def wrapperProps = file("${task.project.projectDir}/gradle/wrapper/gradle-wrapper.properties")
                if (wrapperProps.exists()) {
                    wrapperProps.text = wrapperProps.text.replaceAll(
                        /distributionUrl=.*/,
                        'distributionUrl=https\\://services.gradle.org/distributions/gradle-8.14.1-all.zip'
                    )
                }
            }
        }
    }
}
""")

    print(f"Created {init_script_path} to force Gradle 8.14.1")

    # Output environment variables for GitHub Actions
    if "GITHUB_ENV" in os.environ:
        with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"JAVA_HOME={jdk_path}\n")
            f.write(f"GRADLE_USER_HOME={gradle_home}\n")
            # Force Gradle to use specific Java version
            f.write(f"GRADLE_OPTS=-Dorg.gradle.java.home={jdk_path}\n")
        print("Environment variables written to GITHUB_ENV")
        print("Set JAVA_HOME, GRADLE_USER_HOME, and GRADLE_OPTS")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Configure Unity Android build settings for CI"
    )
    parser.add_argument(
        "--editor-version",
        required=True,
        help="Unity editor version (e.g., 2021.3.45f2)"
    )
    parser.add_argument(
        "--gradle-path",
        required=True,
        help="Path to Gradle installation directory"
    )
    parser.add_argument(
        "--jdk-path",
        required=True,
        help="Path to JDK installation directory"
    )
    args = parser.parse_args()

    configure_gradle_env(args.gradle_path, args.jdk_path, args.editor_version)
