/*
 * This source file was generated by the Gradle 'init' task
 */
package io.embrace.android.unitywrapper

import io.embrace.android.embracesdk.Embrace
import io.embrace.android.embracesdk.UnityInternalInterface

class Wrapper {
    private var _embrace : Embrace? = null
    private val embrace : Embrace
        get() {
            if (_embrace == null) {
                _embrace = Embrace.getInstance()
            }
            return _embrace!!
        }
    
    private var _unityInternalInterface : UnityInternalInterface? = null
    private val unityInternalInterface : UnityInternalInterface
        get() {
            if (_unityInternalInterface == null) {
                _unityInternalInterface = embrace.getUnityInternalInterface()
                if (_unityInternalInterface == null) {
                    throw IllegalStateException("UnityInternalInterface is still null after calling Embrace.getUnityInternalInterface()")
                }
            }
            return _unityInternalInterface!!
        }

    fun someLibraryMethod(): Boolean {
        return true
    }

    fun getInstance() : Embrace {
        return Embrace.getInstance()
    }

    fun setUnityMetaData(unityVersion: String?, buildGuid: String?, unitySdkVersion: String?) {
        println("Setting Unity Meta Data")
        unityInternalInterface.setUnityMetaData(unityVersion, buildGuid, unitySdkVersion)
    }
}
