name: EmbraceUnityiOS
options:
  deploymentTarget:
    iOS: "13.0"
schemes:
  EmbraceUnityiOS:
    build:
      targets:
        EmbraceUnityiOS: all
targets:
  EmbraceUnityiOS:
    platform: iOS
    info:
      path: Info.plist
      deploymentTarget: "13.0"
      properties:
        CFBundleIdentifier: com.embraceio.unityios
        CFBundleName: EmbraceUnityiOS
    settings:
      base:
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        SKIP_INSTALL: true
        CODE_SIGNING_ALLOWED: NO
    sources:
      - Sources
    type: framework
    dependencies:
      - framework: ./xcframeworks/EmbraceCaptureService.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceCommonInternal.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceConfigInternal.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceConfiguration.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceCore.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceCrash.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceCrashlyticsSupport.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceIO.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceOTelInternal.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceObjCUtilsInternal.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceSemantics.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceStorageInternal.xcframework
        embed: true
      - framework: ./xcframeworks/EmbraceUploadInternal.xcframework
        embed: true
      - framework: ./xcframeworks/GRDB.xcframework
        embed: true
      - framework: ./xcframeworks/KSCrashCore.xcframework
        embed: true
      - framework: ./xcframeworks/KSCrashRecording.xcframework
        embed: true
      - framework: ./xcframeworks/KSCrashRecordingCore.xcframework
        embed: true
      - framework: ./xcframeworks/OpenTelemetryApi.xcframework
        embed: true
      - framework: ./xcframeworks/OpenTelemetrySdk.xcframework
        embed: true
