lane :pre_build do
    puts "Current directory: #{Dir.pwd}"
    puts "Directory contents: #{Dir.entries(Dir.pwd)}"
    puts "parent directory: #{File.expand_path('..', Dir.pwd)}"
    puts "parent contents: #{Dir.entries(File.expand_path('..', Dir.pwd))}"
    puts "Pparent directory: #{File.expand_path('../..', Dir.pwd)}"
    puts "Pparent contents: #{Dir.entries(File.expand_path('../..', Dir.pwd))}"
end
