name: Unity Test
description: Run the Unity SDK tests.

inputs:
  build_target:
    description: >
      Unity build target ("android" or "ios"). If omitted, both build targets
      will be run.
  editor_version:
    description: Version of the Unity editor.
    required: true
  editor_changeset:
    description: Changeset for the Unity editor version.
    required: true
  license_email:
    description: Email to use for Unity activation.
    required: true
  license_password:
    description: Password to use for Unity activation.
    required: true
  license_serial:
    description: Serial to use for Unity activation.
    required: true
  project:
    description: Name of the project folder in UnityProjects
    required: true

runs:
  using: composite
  steps:
    - name: Set environment variables from inputs
      shell: bash
      env:
        BUILD_TARGET: ${{ inputs.build_target }}
        EDITOR_CHANGESET: ${{ inputs.editor_changeset }}
        EDITOR_VERSION: ${{ inputs.editor_version }}
        ARTIFACTS_DIR: ${{ runner.temp }}/test-exports
      run: |
        make github_env_vars | tee -a $GITHUB_ENV
    - name: Cache Library folder
      uses: actions/cache@v4
      with:
        path: ./UnityProjects/${{ inputs.project }}/Library
        key: Library-${{ inputs.project }}-Android
        restore-keys: |
          Library-${{ inputs.project }}-
          Library-
    - name: Setup Swift (Linux)
      if: ${{ inputs.build_target != 'android' }}
      uses: swift-actions/setup-swift@d4537ff835c9778c934e48f78639e270edd5839e
      with:
        swift-version: '5.10.1'
    - name: Export SPM vars
      shell: bash
      run: |
        echo "SPM_DIR=${GITHUB_WORKSPACE}/io.embrace.sdk/iOS/EmbraceUnityiOS" >> "$GITHUB_ENV"
    - name: Cache SPM
      if: ${{ inputs.build_target != 'android' }}
      uses: actions/cache@v4
      with:
        path: |
          "${{ env.SPM_DIR }}/.build"
          "${{ env.SPM_DIR }}/Package.resolved"
        key: spm-${{ runner.os }}-swift5.10-${{ hashFiles(format('{0}/Package.resolved', env.SPM_DIR)) }}
        restore-keys: |
          spm-${{ runner.os }}-swift5.10-
    - name: Resolve iOS deps (SPM)
      if: ${{ inputs.build_target != 'android' }}
      shell: bash
      run: |
        swift package --package-path "$SPM_DIR" --disable-sandbox resolve
    - name: Install Unity Hub
      shell: bash
      run: |
        make install_hub
    - name: Install editor
      shell: bash
      run: |
        make install_editor
    - name: Run tests
      shell: bash
      env:
        UNITY_EMAIL: ${{ inputs.license_email }}
        UNITY_PASSWORD: ${{ inputs.license_password }}
        UNITY_SERIAL: ${{ inputs.license_serial }}
      run: |
        make test
    - name: Output Test Results
      shell: bash
      run: |
        cd ./build/test-results
        cat ./*
    - name: Render Test Report
      uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
      with:
        name: ${{ inputs.editor_version }} Tests
        path: ./build/test-results/*.xml
        reporter: dotnet-nunit
    - name: Output Test Logs
      shell: bash
      run: |
        cd ./build/test-logs
        cat ./*
        
    - name: Upload exported files
      if: ${{ inputs.build_target != 'android' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-exports
        path: ${{ env.ARTIFACTS_DIR }}/
        
    - name: Add link + preview to summary
      if: ${{ inputs.build_target != 'android' }}
      shell: bash
      run: |
        echo "## Test export" >> $GITHUB_STEP_SUMMARY
        echo "- Artifact: **test-exports**" >> $GITHUB_STEP_SUMMARY
        echo "- Download: [Go to run artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "<details><summary>Preview my-output.json</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        printf '```json\n' >> $GITHUB_STEP_SUMMARY
        sed -n '1,200p' "$ARTIFACTS_DIR/my-output.json" >> $GITHUB_STEP_SUMMARY
        printf '\n```\n' >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
        
    - name: Uninstall editor
      shell: bash
      run: |
        make uninstall_editor
