/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.embrace.android.embracesdk.Embrace

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun getInstance() : Embrace {
        return Embrace.getInstance()
    }
}
