name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
