name: Publish Unity SDK from Public Repo

env:
  PACKAGE_REPO_PATH: 'embrace-unity-sdk-internal'
  PACKAGE_DIRECTORY: './io.embrace.sdk'
  PACKAGE_JSON_PATH: './io.embrace.sdk/package.json'
  PACKAGE_CHANGELOG_PATH: './io.embrace.sdk/CHANGELOG.md'
  EDM_DEPENDENCIES_PATH: './io.embrace.sdk/Editor/EmbraceSDKDependencies.xml'
  DOCS_REPO_PATH: 'embrace-docs'
  DOCS_CHANGELOG_PATH: 'docs/unity/changelog.md'
  DOCS_CONFIG_PATH: 'embrace.json'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - alyssa/iOS/6.5.1
      - non-existent-branch

jobs:
  generate_iOS_xcframeworks:
    name: Generate Unity iOS XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Download iOS SDK
        run: |
          cd ./Embrace\ Unity\ iOS\ Interface/
          ./update_iOS_to_latest.sh
      - name: Generate iOS XCFrameworks
        run: |
          cd ./Embrace\ Unity\ iOS\ Interface/
          ./build_xcframework.sh
      - name: Upload XCFrameworks
        uses: actions/upload-artifact@v4
        with:
          name: EmbraceUnityXCFramework
          path: ./Embrace\ Unity\ iOS\ Interface/build/EmbraceUnityiOS.xcframework
          retention-days: 1