name: Publish Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  verify_release:
    name: Verify release
    runs-on: ubuntu-22.04
    outputs:
      release_version: ${{ steps.verify_release.outputs.release_version }}
      release_commit_sha: ${{ steps.verify_release.outputs.release_commit_sha }}
      is_release_candidate: ${{ steps.verify_release.outputs.is_release_candidate }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - name: Verify the release
        id: verify_release
        run: |
          python3 .github/scripts/release.py verify
      - name: Validate access to version data service
        uses: embrace-io/public-actions/upload-sdk-version@88167cd1a3fce3418e26c8c842026e6dfab99e41
        with:
          platform: 'unity'
          version: '0.0.0' # Just validating the token, so the version doesn't matter
          dryRun: true
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
  build_release:
    name: Build release
    needs:
      - verify_release
    uses: ./.github/workflows/build.yml
    secrets: inherit
  create_github_release:
    name: Create GitHub release
    needs:
      - verify_release
      - build_release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      PACKAGE_NAME: EmbraceSDK_${{ needs.verify_release.outputs.release_version }}.unitypackage
      RELEASE_TAG: v${{ needs.verify_release.outputs.release_version }}
      RELEASE_VERSION: ${{ needs.verify_release.outputs.release_version }}
      IS_RELEASE_CANDIDATE: ${{ needs.verify_release.outputs.is_release_candidate }}
    steps:
      - name: Fetch the unitypackage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
      - name: Disable GitHub CLI Prompt if Enabled
        run: |
          if [ "$(gh config get prompt)" = "enabled" ]; then
            gh config set prompt disabled
          fi
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if gh release view --repo embrace-io/embrace-unity-sdk $RELEASE_TAG > /dev/null 2>&1; then
            echo "Release $RELEASE_TAG already exists"
            exit 1
          fi
          echo "Creating release $RELEASE_TAG"
          PRERELEASE=""
          if [ "$IS_RELEASE_CANDIDATE" == "true" ]; then
            PRERELEASE="--prerelease"
          fi
          gh release create "$RELEASE_TAG" "$PACKAGE_NAME" $PRERELEASE --draft --title "$RELEASE_TAG" --repo embrace-io/embrace-unity-sdk --verify-tag
  create_internal_release:
    name: Create internal release
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - verify_release
      - build_release
    env:
      RELEASE_VERSION: ${{ needs.verify_release.outputs.release_version }}
      IS_RELEASE_CANDIDATE: ${{ needs.verify_release.outputs.is_release_candidate }}
    steps:
      - name: Record SDK version history
        if: needs.verify_release.outputs.is_release_candidate != 'true'
        uses: embrace-io/public-actions/upload-sdk-version@88167cd1a3fce3418e26c8c842026e6dfab99e41
        with:
          platform: 'unity'
          version: ${{ env.RELEASE_VERSION }}
          dryRun: false
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
