name: Run Tests on Public Repository

on:
  workflow_dispatch:
    inputs:
      includeLinux:
        type: boolean
        required: false
        default: true
      includeWindows:
        type: boolean
        required: false
        default: false
      includeMac:
        type: boolean
        required: false
        default: true

  workflow_call:
    inputs:
      includeLinux:
        type: boolean
        required: false
        default: true
      includeWindows:
        type: boolean
        required: false
        default: false
      includeMac:
        type: boolean
        required: false
        default: true
  push:
    branches:
      - Workflow-Remap

jobs:
  tests-linux:
    #if: ${{ github.event.inputs.includeLinux }}
    #temporarily disabled while we work on the Mac tests and CI
    if: always()
    name: Test SDK on Linux
    uses: ./.github/workflows/test_project_linux.yml
    secrets: inherit

  tests-macos:
    #if: ${{ github.event.inputs.includeMac }}
    if: always()
    name: Test SDK on MacOS
    uses: ./.github/workflows/test_project_macos.yml
    secrets: inherit

  # This job is disabled while we work on the Windows tests and CI
  tests-windows:
    if: false
    name: Test SDK on Windows
    uses: ./.github/workflows/test_project_windows.yml
    secrets: inherit